### ISSUE TITLE
🏥 Replace Pills with Treatments

### ISSUE THREAD

**Issue by jonathan-robertson** [jonathan-robertson/amnesia#69]
## Idea
- No more pills
- Receive treatment at any trader for a cost
- Cost of treatment goes up based on player's current level

## Considering
- Add option to heal other ailments at trader (flat rate, instant heal)

## Tasks
- [x] add dialog options
- [x] add system for purchasing and getting change
- [x] remove fragile memory when purchase of treatment is successful
- [x] sync and display sale price of treatment
- [x] remove memory pills
- [x] include responses (toolbelt tips, sounds) for all conversation terminators (or use quests)
- [x] update cost colors to match quest highlight color
- [ ] test with all other mods enabled

**Comment by jonathan-robertson** [comment]
Confirmed cvars can be injected into dialog responses

**Comment by jonathan-robertson** [comment]
Requirements can be set to use 2 of 1 handling patterns:

```cs
public enum RequirementVisibilityTypes
{
	AlternateText,
	Hide
}
```
*only `Hide` has been used in vanilla*

**Comment by jonathan-robertson** [comment]
Several requirement types, but only `Buff` would be helpful:
```cs
public enum RequirementTypes
{
	Buff,
	QuestStatus,
	QuestsAvailable,
	QuestTier,
	QuestTierHighest,
	QuestEditorTag,
	Skill,
	Admin,
	DroneState,
	DroneStateExclude
}
```

**Comment by jonathan-robertson** [comment]
```cs
	public override bool CheckRequirement(EntityPlayer player, EntityNPC talkingTo)
	{
		return false;
	}
```
Daaaaaaaaaaang :[
this does not work and will never work; `DialogRequirementBuff` must not have ever been fully implemented
