### ISSUE TITLE
🧠 Reset to Skills Acquired at Start Level

### ISSUE THREAD

**Issue by jonathan-robertson** [jonathan-robertson/amnesia#70]
## Description

Instead of resetting and freeing up skill points (free forgetting elixir effect), record the 49th skill point set (or record at player level 50?) and apply that config upon reset.

## Tasks
- [x] Record each skill invested by each player to files
- [x] Save skill progress to a file, load it from a file
- [x] Allow viewing of each skill via console
- [x] Track unspent skill points
  - wait... a final sync package sends when the player dies, right? So... we don't need to track this during gameplay, right?
  - except for... perhaps the forgetting elixir effect? If this is fired from the server, does this mess things up? Shouldn't. Only rewinding should care about currently unused skill points; full memory reset would calculate total skill points expected. 
- [x] Update reset pattern to roll back to a given level, first consuming unspent points, then consuming spent points 
- [x] Add integrity check on player data file sync
- [x] Reset with core tools, then replay skills chosen, spending as many skill points as able

## Gold Plating?
- [ ] Add console commands to add x, remove x levels
- [x] Add reconciliation logic for moments when the server failed to record updates?
- [ ] Track skill points added via game events?
- [ ] Track skill points added via quests?

## Related
- #72
