### ISSUE TITLE
🏥 Add Memory Therapy to Trader

### ISSUE THREAD

**Issue by jonathan-robertson** [jonathan-robertson/amnesia#71]
- Remove forgetting elixir item
- Add option to respec at trader
- Set cost based on level, maybe 1/2 the cost of your memory recovery

## Tasks
- [x] add console command to trigger respec
- [x] remove forgetting elixir from loot
- [x] remove forgetting elixir from traders
- [x] add Therapy option at trader
- [x] add Therapy price
- [x] add supporting dialog and purchase processes for Therapy

## Tests
- [x] reset skill points via Therapy properly flushes purchased skills and returns skill points
